"""Core domain models for the ddt trading toolkit.

Defines the two primary data objects that flow through the system:
:class:`NewsEvent` (an ingested news item) and :class:`TradeProposal`
(a suggested trade derived from one or more events).
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List
from uuid import uuid4


def utc_now() -> str:
    """Return the current UTC timestamp as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


@dataclass
class NewsEvent:
    """A normalised news item ingested from any upstream source.

    Attributes:
        source: Provider name (e.g. ``'polygon'``, ``'sample'``).
        headline: Original headline text.
        summary: Brief description or article lead.
        url: Canonical link to the full article.
        tickers: Ticker symbols mentioned in the article.
        asset_classes: Asset classes the article relates to.
        event_id: Unique identifier (auto-generated UUID).
        created_at: ISO-8601 UTC timestamp of creation.
        metadata: Arbitrary extra fields added during normalisation.
    """
    source: str
    headline: str
    summary: str
    url: str
    tickers: List[str] = field(default_factory=list)
    asset_classes: List[str] = field(default_factory=list)
    event_id: str = field(default_factory=lambda: str(uuid4()))
    created_at: str = field(default_factory=utc_now)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialise the event to a plain dictionary."""
        return asdict(self)


@dataclass
class TradeProposal:
    """A proposed trade generated by a strategy.

    Attributes:
        symbol: Ticker symbol to trade.
        side: ``'buy'`` or ``'sell'``.
        rationale: Human-readable explanation for the trade.
        confidence: Confidence score in the range ``[0, 1]``.
        source_event_ids: IDs of the :class:`NewsEvent` instances that
            triggered this proposal.
        asset_class: Asset class (default ``'equity'``).
        quantity_hint: Suggested quantity or ``'REVIEW_REQUIRED'``.
        status: Lifecycle status (``'draft'``, ``'approved'``, etc.).
        proposal_id: Unique identifier (auto-generated UUID).
        created_at: ISO-8601 UTC timestamp of creation.
        risk_notes: Warnings produced by risk evaluation.
        metadata: Arbitrary extra fields.
    """
    symbol: str
    side: str
    rationale: str
    confidence: float
    source_event_ids: List[str]
    asset_class: str = 'equity'
    quantity_hint: str = ''
    status: str = 'draft'
    proposal_id: str = field(default_factory=lambda: str(uuid4()))
    created_at: str = field(default_factory=utc_now)
    risk_notes: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialise the proposal to a plain dictionary."""
        return asdict(self)
