"""Core data models for news events and trade proposals."""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List
from uuid import uuid4


def utc_now() -> str:
    """Return the current UTC time as an ISO-8601 string."""
    return datetime.now(timezone.utc).isoformat()


@dataclass
class NewsEvent:
    """A single news item linked to one or more ticker symbols.

    Each event is assigned a unique ``event_id`` on creation and carries
    arbitrary metadata (publisher info, sentiment, tags) used downstream
    by strategies and ranking logic.
    """

    source: str
    headline: str
    summary: str
    url: str
    tickers: List[str] = field(default_factory=list)
    asset_classes: List[str] = field(default_factory=list)
    event_id: str = field(default_factory=lambda: str(uuid4()))
    created_at: str = field(default_factory=utc_now)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the event to a plain dictionary."""
        return asdict(self)


@dataclass
class TradeProposal:
    """A proposed trade generated by a strategy in response to news events.

    Proposals progress through a status lifecycle (draft -> approved ->
    submitted -> filled) managed by the approval service.  Risk notes
    and guardrail checks are attached before the proposal is surfaced
    to the operator.
    """

    symbol: str
    side: str
    rationale: str
    confidence: float
    source_event_ids: List[str]
    asset_class: str = 'equity'
    quantity_hint: str = ''
    status: str = 'draft'
    proposal_id: str = field(default_factory=lambda: str(uuid4()))
    created_at: str = field(default_factory=utc_now)
    risk_notes: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Serialize the proposal to a plain dictionary."""
        return asdict(self)
